config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'sites'

  root to: 'home#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'join', to: 'devise/registrations#new'
  end

  get 'rules', to: 'home#rules', as: 'rules'
  get 'list', to: 'sites#index', as: 'list'
  get 'sites/:id', to: 'sites#show', as: 'sites'

  get 'admin', to: 'admin#index', as: 'admin'
  post 'admin/site/approve', to: 'admin#approve', as: 'admin_approve'
  post 'admin/site/set_inactive', to: 'admin#set_inactive', as: 'admin_set_inactive'
  get 'admin/site/:id', to: 'admin#edit', as: 'admin_edit'
  post 'admin/site/:id', to: 'admin#update', as: 'admin_update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  source Rails.root.join("config/app.yml")
  namespace Rails.env
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :email, :display_name, :site_name, :site_url, :site_description
  validates_uniqueness_of :email

  has_one_attached :screenshot

  def next
    next_user = User.where('id > ?', self.id).order(id: :desc).where(is_active: true).first
    if next_user.nil?
      next_user = User.where(is_active: true).order(id: :desc).first
    end

    next_user
  end

  def prev
    prev_user = User.where('id < ?', self.id).order(id: :desc).where(is_active: true).last
    if prev_user.nil?
      prev_user = User.where(is_active: true).order('id desc').last
    end

    prev_user
  end

  def code_installed
    # page should contain a link to the ring, the next link, and the prev link
  end

  def get_verification
    site_content = Nokogiri::HTML(HTTParty.get(self.site_url))
    verification = site_content.xpath("//meta[@name='#{Setting.ring_name.downcase.parameterize}_verification']")
    if verification.length > 0 and verification.attr('content').text.to_i == self.id
      return true
    end

    return false
  end

  def is_new?
    if self.last_reviewed.nil?
      return true
    end

    return false
  end

  def needs_review?
    if self.last_reviewed.present? and self.last_reviewed < self.user_last_updated
      return true
    end

    return false
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :check_admin

  def index
    @new_sites = User.where(last_reviewed: nil)
    @sites_needing_review = User.where('last_reviewed != null AND updated_at > last_reviewed').order(:id)
    @sites = User.all.order(:id)
  end

  def settings

  end

  def update_settings
    Setting.ring_name = params[:ring_name]
    Setting.ring_description = params[:ring_description]
    Setting.ring_rules = params[:ring_rules]
    Setting.high_security = params[:high_security]
    redirect_to admin_settings_path
  end

  def edit
    @site = User.find(params[:id])
  end

  def update
    @site = User.find(params[:id])
    if @site.update_attributes(site_params)
      flash[:success] = "Site \"#{@site.site_name}\" updated successfully."
      redirect_to admin_path and return
    else
      flash[:error] = "There was an error updating the site \"#{@site.site_name}.\""
      redirect_to admin_edit_path(@site) and return
    end
  end

  def approve
    @site = User.find(params[:site])
    @site.last_reviewed = DateTime.now
    @site.is_active = true
    if @site.save!
      return true
    end

    return false
  end

  def set_inactive
    @site = User.find(params[:site])
    @site.last_reviewed = DateTime.now
    @site.is_active = false
    if @site.save!
      return true
    end

    return false
  end

  def destroy
    @site = User.destroy(params[:id])
    flash[:success] = "Site \"#{@site.site_name}\" has been removed."
    redirect_to admin_path
  end

  protected

  def check_admin
    unless current_user.is_admin?
      redirect_to root_path
    end
  end

  private

  def site_params
    params.require(:user).permit(:site_name, :site_url, :site_description, :is_active, :screenshot)
  end

  def user_params
    params.require(:user).permit(:display_name, :email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:display_name, :site_name, :site_url, :site_description])
    devise_parameter_sanitizer.permit(:account_update, keys: [:display_name, :site_name, :site_url, :site_description])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @sites = User.order("RANDOM()").first(3)
  end

  def rules

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_inactive_sign_up_path_for(resource)
    scope = Devise::Mapping.find_scope!(resource)
    router_name = Devise.mappings[scope].router_name
    context = router_name ? send(router_name) : self
    context.respond_to?(:new_user_session_path) ? context.new_user_session_path : "/users/sign_in"
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:display_name, :site_name, :site_url, :site_description, :screenshot])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:display_name, :site_name, :site_url, :site_description, :screenshot])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = User.all.order(:id)
  end

  def show
    @site = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/_site.slim
li[class="#{classname}"]
  - if site.screenshot.attached?
  .image
    = image_tag url_for(site.screenshot)

  h3 #{site.site_name}
  p
    strong User:
    = " #{site.display_name}"

  p
    strong Site Address:
    = link_to " #{site.site_url}", site.site_url, rel: 'external', target: '_blank'

  p
    strong Ownership Verified:
    = " #{site.get_verification ? 'Yes' : 'No'}"

  p
    strong Code Detected:

  p
    strong Site Description:

  .description
    = site.site_description

  nav.admin-links
    ul
      li
        = link_to "Edit", admin_edit_path(site)
      - unless site.is_active?
        li
          = link_to "Approve", "#", class: 'approve-link', 'data-site': site.id
      - else
        li
          = link_to "Set Inactive", "#", class: "active-link", 'data-site': site.id

app/views/admin/edit.slim
h2 Editing Site: #{@site.site_name}

= form_for @site, url: admin_update_path, method: 'POST' do |f|

  .form-row
    = f.label :site_name
    = f.text_field :site_name

  .form-row
    = f.label :site_url
    = f.url_field :site_url

  .form-row
    = f.label :site_description
    = f.text_area :site_description

  .form-row
    = f.label :screenshot
    = f.file_field :screenshot

  .form-row
    = f.label :is_active
    = f.check_box :is_active

  .form-row
    = f.submit "Save"

app/views/admin/index.slim
h2 Administration

- if @new_sites.present?
  h2 Pending Approval
  ul#admin-list
    - @new_sites.each do |site|
      = render partial: 'site', locals: {site: site, classname: 'new'}

- if @sites_needing_review.present?
  h2 Need Review
  ul#admin-list
    - @sites_needing_review.each do |site|
      = render partial: 'site', locals: {site: site, classname: 'needs-review'}

- if @sites.present?
  h2 All Sites
  ul#admin-list
    - @sites.each do |site|
      = render partial: 'site', locals: {site: site, classname: site.needs_review? ? 'needs-review' : (site.is_new? ? 'new' : '')}

javascript:
  $('body').on('click', '.approve-link', function(e) {
    e.preventDefault();
    var link = $(this);
    $.ajax({
      url: "#{admin_approve_path}",
      method: 'POST',
      data: {
        site: $(this).data('site'),
        authenticity_token: "#{form_authenticity_token}"
      },
      success: function(data) {
        link.parents('li').parents('li').removeClass('needs-review').removeClass('new');
        link.html('Set Inactive');
        link.removeClass('active-link').addClass('approve-link');
      }
    });
  });

  $('body').on('click', '.active-link', function(e) {
    e.preventDefault();
    var link = $(this);
    $.ajax({
      url: "#{admin_set_inactive_path}",
      method: 'POST',
      data: {
        site: $(this).data('site'),
        authenticity_token: "#{form_authenticity_token}"
      },
      success: function(data) {
        console.log('hello world');
        link.parents('li').parents('li').addClass('needs-review');
        link.html('Approve');
        link.removeClass('approve-link').addClass('active-link');
      }
    });
  });

app/views/admin/settings.slim
h2 Site Settings

= form_tag 'update_settings', method: 'POST'

  .form-row
    = label_tag "Site Name", for: :ring_name
    = text_field_tag :ring_name, Setting.ring_name

  .form-row
    = label_tag "Site Description", for: :ring_description
    = text_area_tag :ring_description, Setting.ring_description

  .form-row
    = label_tag "Site Rules", for: :ring_rules
    em A list of membership rules that will appear on the Rules page.
    = text_area_tag :ring_rules, Setting.ring_rules

  .form-row
    = label_tag "Use higher security?", for: :high_security
    em When checked, when members update their site information, their site will be marked inactive until it's reviewed. Requires higher admin maintenance.
    = check_box_tag :high_security, Setting.high_security

  .form-row
    = submit_tag "Save"

app/views/home/index.slim
#ring-description
  = Setting.ring_description

  - unless current_user.present?
    .button-row.center
      = link_to "Apply to Join", new_user_registration_path, class: 'button'

- if @sites.present?
  h2 Random Links

  ul#links-list
    - @sites.each do |site|
      li
        - if site.screenshot.attached?
          .image
            = link_to image_tag(url_for(site.screenshot)), site.site_url, rel: 'external', target: '_blank'
        h3
          = link_to site.site_name, site.site_url, rel: 'external', target: '_blank'

        p.description
          = AutoExcerpt.new(site.site_description, {words: 25, strip_paragraphs: true})
          = " "
          = link_to "Read More", sites_path(site.id)

app/views/home/rules.slim
h2 Rules

= Setting.rules

app/views/layouts/application.slim
doctype html
html
  head
    title Friendship Circle
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body
  header#header
    h1
      a href="/" #{Setting.ring_name}
    nav#navigation
      ul
        li
          = link_to "Home", root_path
        li
          = link_to "List", list_path
        li
          = link_to "Rules", rules_path
        - if current_user.nil?
          li
            = link_to "Join", new_user_registration_path
          li
            = link_to "Log In", new_user_session_path

        - if current_user.present?
          li
            - if current_user.is_admin?
              a href="/admin" Manage

            - else
              a href="/manage" Manage

          li
            form action="/logout" method="POST" class="invisible-form"
              input type="submit" class="link-button" value="Log Out"


  main#main
    - if flash.present?
      ul.messages
        - flash.each do |msg_type, msg|
          li class="#{msg_type}" #{msg}
    = yield

app/views/sites/index.slim
h2 All Links

- if @sites.present?
  ul#links-list
    - @sites.each do |site|
      li
        h3
          = link_to site.site_name, site.site_url, rel: 'external', target: '_blank'

        p.description #{AutoExcerpt.new(site.site_description, {words: 25, strip_paragraphs: true})}

app/views/sites/show.slim
.profile
  h2
    a href="#{@site.site_url}" rel="external" target="_blank" #{@site.site_name}

  p
    strong Owner:
    = " #{@site.display_name}"

  .description
    = @site.site_description

  nav.site-links
    - if @site.prev.present?
      = link_to "Prev: #{@site.prev.site_name}", sites_path(@site.prev.id), class: 'prev-link'
    - if @site.next.present?
      = link_to "Next: #{@site.next.site_name}", sites_path(@site.next.id), class: 'next-link'